### ISSUE TITLE
Not able to draw two lines in one graph

### ISSUE THREAD

**Issue by narri007** [Boris-Em/BEMSimpleLineGraph#227] opened 2015-08-26 01:00 UTC
I was trying to draw two line graphs in one plot using BEMLIneGraph , but not able to do it with this API, can anyone help me on this.
~Many thanks

**Comment by Boris-Em** [comment] 2015-08-26 16:39
Hi @narri007,
Multiple lines are currently not supported by BEMSimpleLineGraph.
Closed as duplicate of #44.

**Closed by Boris-Em** 2015-08-26 16:39 UTC
Labels: duplicate
