### ISSUE TITLE
Selecting a point when all data loads

### ISSUE THREAD

**Issue by ganjmeng** [Boris-Em/BEMSimpleLineGraph#266] opened 2016-06-13 08:40 UTC
how to selected a point when the date load?

I want to selected the last point in the line when the data load
![image](https://cloud.githubusercontent.com/assets/12026835/16001579/6b3bfa7e-3185-11e6-8a26-6042420fabab.png)

**Comment by Sam-Spencer** [comment] 2016-07-02 20:04
If I understand your question correctly, this appears to be a duplicate of Issue #258. It is currently not possible to programmatically select a point on the graph. However, BEMSimpleLineGraph can make calls to your delegate object when the graph finishes loading (`lineGraphDidFinishLoading:`) and when it finishes drawing (`lineGraphDidFinishDrawing:`).

**Closed by Sam-Spencer** 2016-07-02 20:04 UTC
Labels: duplicate, enhancement, question
