### ISSUE TITLE
first and last xAxis labels out of view

### ISSUE THREAD

**Issue by ilandbt** [Boris-Em/BEMSimpleLineGraph#137] opened 2015-03-12 08:55 UTC
My first and last X-Axis labels are half out of the view. Is there a way to make it show the whole label?

**Comment by laeryn** [comment] 2015-03-13 05:03
I have the same issue

**Comment by Sam-Spencer** [comment] 2015-03-14 00:54
Closing as duplicate of #67.

**Closed by Sam-Spencer** 2015-03-14 00:54 UTC
Labels: duplicate
