### ISSUE TITLE
How can I reduce the distance between each label?

### ISSUE THREAD

**Issue by Cokile** [Boris-Em/BEMSimpleLineGraph#197] opened 2015-04-04 07:37 UTC
My line graph is a little big for the small screen(like iPhone4S), I think maybe reduce the distance between each label can display the whole graph.

Can I do that? If the answer is yes, how to do that?

**Comment by Sam-Spencer** [comment] 2015-04-06 21:03
We would like to encourage you to post this kind of question directly on StackOverflow using the [BEMSimpleLineGraph tag](http://stackoverflow.com/questions/tagged/bemsimplelinegraph).

We would like to keep GitHub issues strictly for bugs, feature requests, enhancements, etc. StackOverflow also has a higher discoverability and re-usability than GitHub issues, meaning that it would be easier for users who run into the same problem to find a solution.

In fact, you can [ask your question right here](http://stackoverflow.com/questions/ask). Make sure to add the correct tags.

***

You may want to look into AutoLayout to properly size and position your graph. If the labels are still not laying out correctly, please refer to the `numberOfGapsBetweenLabelsOnLineGraph:` delegate method, as [documented in the Wiki](https://github.com/Boris-Em/BEMSimpleLineGraph/wiki/Delegate#x-axis).

If you have correctly implemented and tried both of the above solutions, then this question is likely a duplicate of issue #67.

**Closed by Sam-Spencer** 2015-04-06 21:03 UTC
